### ISSUE TITLE
ModuleNotFoundError: No module named 'Crypto'

### ISSUE THREAD

**Issue by xthunderL** [sepehr-mohseni/Blockchain#1]
Traceback (most recent call last):
  File "C:\Users\acer\Documents\Blockchain-main\node.py", line 4, in <module>  
    from wallet import Wallet
  File "C:\Users\acer\Documents\Blockchain-main\wallet.py", line 1, in <module>
    from Crypto.PublicKey import RSA
ModuleNotFoundError: No module named 'Crypto'

I have installed pycryptodome .

**Comment by sepehr-mohseni** [comment]
Hi. can you do the following and reply this issue with results?

- uninstall 'pycryptodome' with this command: 'pip3 uninstall pycryptodome' && 'pip3 uninstall crypto' (if is installed)
- install 'pycrypto' with this command: 'pip3 install pycrypto'
- import library in 'wallet.py' file: 'from Crypto.PublicKey import RSA' if is removed

**Comment by sepehr-mohseni** [comment]
> Traceback (most recent call last):
> File "C:\Users\acer\Documents\Blockchain-main\node.py", line 4, in
> from wallet import Wallet
> File "C:\Users\acer\Documents\Blockchain-main\wallet.py", line 1, in
> from Crypto.PublicKey import RSA
> ModuleNotFoundError: No module named 'Crypto'
> 
> I have installed pycryptodome .

Hi. can you do the following and reply this issue with results?

uninstall 'pycryptodome' with this command: 'pip3 uninstall pycryptodome' && 'pip3 uninstall crypto' (if is installed)
install 'pycrypto' with this command: 'pip3 install pycrypto'
import library in 'wallet.py' file: 'from Crypto.PublicKey import RSA' if is removed

**Comment by xthunderL** [comment]
I could  not install 'pycrypto' as it shows error also please check this out : https://github.com/sfbahr/PyCrypto-Wheels

**Comment by sepehr-mohseni** [comment]
> I could not install 'pycrypto' as it shows error also please check this out : https://github.com/sfbahr/PyCrypto-Wheels

Hello. thank you for the link. I will try to bring this up to project manager. because this project is part of a bigger project which i open sourced. its working fine right now on our systems but as this package is not used anymore i will try to refactor it on our system. Also feel free to contribute for refactoring to this repo. you can make pull request to this project and i will appreciate it.

**Comment by xthunderL** [comment]
Hello, Yes I would love to refactor the project but would you mind helping me out with running this project. I am Computer Science Engineering Student so it's not that easy for me too so, it would be a great help for me if you helped me refactor the code. Just guide me I will do the rest.
